# Generated by Django 5.1.1 on 2024-09-21 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_scheduledemail_last_active_scheduledemail_send_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledemail',
            name='send_date',
        ),
    ]
